import type { INodeProperties } from 'n8n-workflow';
import { actionBookingCreateBooking, resourceBooking } from '../resources.constants';

const showOnlyForBookingCreate = {
  operation: [actionBookingCreateBooking],
  resource: [resourceBooking],
};

export const bookingCreateDescription: INodeProperties[] = [
  {
    displayName: "Import ID",
    name: "externalId",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "Unique import ID for this booking (e.g. ID of the booking in another system)",
    required: true,
  },
  {
    displayName: "Product or Product ID",
    name: "product",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The name or ID of the product to book",
    required: true,
  },
  {
    displayName: "Tickets",
    name: "tickets",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    placeholder: '2x Adult, 1x Child',
    description: "The tickets to book. Must follow the format: '1x Adult, 2x Child, ...'. The name of the ticket must match Peek Pro exactly.",
    required: true,
  },
  {
    displayName: "Date",
    name: "date",
    type: "dateTime",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The date of the booking",
    required: true,
  },
  {
    displayName: "Start Time",
    name: "start",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    placeholder: '4:30pm',
    description: "The start time of the booking as local time (e.g. 4:30pm)",
    required: true,
  },
  {
    displayName: "End Time",
    name: "end",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    placeholder: '5:30pm',
    description: "The end time of the booking as local time (e.g. 5:30pm)",
    required: true,
  },
  {
    displayName: "Customer Name",
    name: "customerName",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The name of the customer",
    required: true,
  },
  {
    displayName: "Customer Email",
    name: "email",
    type: "string",
    placeholder: 'name@email.com',
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The email of the customer",
    required: false,
  },
  {
    displayName: "Customer Phone Number",
    name: "phone",
    type: "string",
    placeholder: '+15555555555',
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The email of the customer",
    required: false,
  },
  {
    displayName: "Notes",
    name: "notes",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The notes for the booking",
    required: false,
  },
  {
    displayName: "Customer Postal Code",
    name: "postalCode",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    description: "The postal code of the customer",
    required: false,
  },
  {
    displayName: "Customer Country",
    name: "country",
    type: "string",
    displayOptions: { show: showOnlyForBookingCreate },
    default: "",
    placeholder: 'US',
    description: "The 2 letter country code of the customer (e.g. 'US' for the United States)",
    required: false,
  },
  {
    displayName: 'Opted Into Marketing',
		name: 'optinMarketing',
		type: "boolean",
    displayOptions: { show: showOnlyForBookingCreate },
		default: false,
		description: 'Whether the customer has opted into marketing emails',
  },
  {
    displayName: 'Opted Into SMS Messages',
		name: 'optinSms',
		type: "boolean",
    displayOptions: { show: showOnlyForBookingCreate },
		default: false,
		description: 'Whether the customer has opted into SMS messages',
  },
  {
    displayName: 'Send Confirmation Emails',
		name: 'shouldSendEmails',
		type: "boolean",
    displayOptions: { show: showOnlyForBookingCreate },
		default: false,
		description: 'Whether to send confirmation emails to the customer',
  },
  {
    displayName: 'Mark Booking As Paid',
		name: 'markBookingAsPaid',
		type: "boolean",
    displayOptions: { show: showOnlyForBookingCreate },
		default: false,
		description: 'Whether to mark the booking as paid',
  },
];
